//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_QLHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNhapKho
    {
        public string MaNK { get; set; }
        public string TenHH { get; set; }
        public string TenNCC { get; set; }
        public decimal SoLuong { get; set; }
        public decimal GiaNhap { get; set; }
        public decimal GiamGia { get; set; }
    }
}
