//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_QLHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupHangHoa
    {
        public string MaGRHang { get; set; }
        public string TenGroupHang { get; set; }
        public string IDNV { get; set; }
        public string TenNV { get; set; }
    }
}
