//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_QLHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public decimal TonKho { get; set; }
        public decimal GiaBan { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public string Anh { get; set; }
        public string GhiChu { get; set; }
        public string TenGRH { get; set; }
        public string TenNCC { get; set; }
        public string IDNV { get; set; }
        public string TenNV { get; set; }
        public bool luu { get; set; }
    }
}
