//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO_QLHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapKho
    {
        public string MaNK { get; set; }
        public System.DateTime NgayNhapKho { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiTao { get; set; }
        public string IDNVT { get; set; }
        public string NguoiCapNhat { get; set; }
        public string IDNVCN { get; set; }
    }
}
